### ISSUE TITLE
Set Git Flow

### ISSUE THREAD

**Issue by dyadyaJora** [itmo-cet-sem/franky#1]
Need to select, set up and describe on wiki our git-flow

**Comment by dyadyaJora** [comment]
https://github.com/itmo-cet-sem/franky/wiki/Git-Flow

**Comment by tcibinan** [comment]
Thanks for your contribution!

I just have a few things to discuss.

1. As long as we don't have several production environments is there really the need to have `release` and `staging` branches? I suppose we can just omit them.

2. There is a discrepancy between [Working process wiki](https://github.com/itmo-cet-sem/franky/wiki/Working-Process) and [Git-Flow one](https://github.com/itmo-cet-sem/franky/wiki/Git-Flow) in terms of the minimal reviewers. One tells 3 and other tells 2 contributors are needed. Probably, the Working process wiki should be adapted as well.

3. I suppose it can be handy to specify associated issue number in branch names such as `feature/issue11_backend-sockets` or `bugfix/issue12_frontend-assembly`.

**Comment by dyadyaJora** [comment]
> Thanks for your contribution!
> 
> I just have a few things to discuss.
> 
> 1. As long as we don't have several production environments is there really the need to have `release` and `staging` branches? I suppose we can just omit them.
> 2. There is a discrepancy between [Working process wiki](https://github.com/itmo-cet-sem/franky/wiki/Working-Process) and [Git-Flow one](https://github.com/itmo-cet-sem/franky/wiki/Git-Flow) in terms of the minimal reviewers. One tells 3 and other tells 2 contributors are needed. Probably, the Working process wiki should be adapted as well.
> 3. I suppose it can be handy to specify associated issue number in branch names such as `feature/issue11_backend-sockets` or `bugfix/issue12_frontend-assembly`.

1 -
2+
3+

**Comment by tcibinan** [comment]
👍
