### ISSUE TITLE
Research Github API

### ISSUE THREAD

**Issue by dyadyaJora** [itmo-cet-sem/franky#11]

**Comment by tcibinan** [comment]
It is required to investigate GitHub platform and its APIs to understand:
- [ ] what kinds of data can we collect by github user name,
- [ ] how can we collect the data from platform in terms of efficiency.

**Comment by tcibinan** [comment]
Brief GitHub API description is available in the corresponding wiki [page](https://github.com/itmo-cet-sem/franky/wiki/GitHub-API).
