### ISSUE TITLE
Travis integration tests

### ISSUE THREAD

**Issue by tcibinan** [itmo-cet-sem/franky#26]
Basic GitHub integration was introduced in #23.

It brought several integration tests which requires GitHub credentials in the environment. Private key in particular. Currently, integration tests are skipped on Travis due to a lack of GitHub credentials.

The integration tests on travis should be enabled with a help of travis [encryption keys](https://docs.travis-ci.com/user/encryption-keys/).

**Comment by dyadyaJora** [comment]
> ... Currently, integration tests are skipped on Jenkins ...


Jenkins or Travis?

**Comment by tcibinan** [comment]
Oops, it was meant to be travis.
