### ISSUE TITLE
[Global] Create project

### ISSUE THREAD

**Issue by dyadyaJora** [itmo-cet-sem/franky#3]
- [ ] Check requirements ...
- [ ] Set up workflow and processes
    - [ ] Set up git flow #1 
    - [ ] Config CI
    - [ ] Create containers for all part of project
- [ ] Design project
    - [ ] Design architecture #2 
- [ ] Research API documentation
    - [ ] Research github api
    - [ ] Research stackoverflow api
    - [ ] Research dockerhub api
- [ ] Frontend Side
    - [ ] Create mockups
    - [ ] Init frontend environment
- [ ] Backend Side
    - [ ] Init server
- [ ] Testing
- [ ] CI&CD
- [ ] Deployment

**Comment by tcibinan** [comment]
Closed because it is not a specific task but a vague and obsolete project check-list.
