### ISSUE TITLE
Research Dockerhub API

### ISSUE THREAD

**Issue by dyadyaJora** [itmo-cet-sem/franky#9]

**Comment by tcibinan** [comment]
It is required to investigate DockerHub platform and its APIs to understand:
- [ ] what kinds of data can we collect by dcokerhub user name,
- [ ] how can we collect the data from the platform in terms of efficiency.

All results of the research should be described in the current issue.

**Comment by tcibinan** [comment]
Done in the offline discussion and later in the team chat.
